#configuration
EXTENDED_MODEL = False
COMM_FAILURE_AWARE = False
SSEP_INT_FUTURE = True
GSEP_ADSB_OUT = True

ENABLE_PURE_CONTROLLERS = False
ENABLE_PURE_AIRSPACE = False


ENABLE_3_GSEP = False
ENABLE_3_GSEP_1_SSEP = False
ENABLE_2_GSEP_2_SSEP = True
ENABLE_1_GSEP_3_SSEP = False
ENABLE_3_GSEP_3_SSEP = False
ENABLE_3_SSEP = False