#configuration
EXTENDED_MODEL = False
COMM_FAILURE_AWARE = False
SSEP_INT_FUTURE = False
GSEP_ADSB_OUT = False

ENABLE_PURE_CONTROLLERS = False
ENABLE_PURE_AIRSPACE = False


ENABLE_3_GSEP = True
ENABLE_3_GSEP_1_SSEP = False
ENABLE_2_GSEP_2_SSEP = False
ENABLE_1_GSEP_3_SSEP = False
ENABLE_3_GSEP_3_SSEP = False
ENABLE_3_SSEP = False